### ISSUE TITLE
how  to  user  httpcontext  in  aspnet core signalr

### ISSUE THREAD

**Issue by tokaika** [maxzhang1985/YOYOFx#11]
HttpContext.Connection.RemoteIpAddress.ToString();
Context.Request.HttpContext.RequestServices.GetService<SecurityManager>().
  cannot  find   in  hub  ..

**Comment by yoyofx** [comment]
RemoteIP 可以在 建议在 Http请求里获取。

新关注我的新项目： https://github.com/yoyofx/yoyogo   使用Go语言复刻ASP.NET Core.
