### ISSUE TITLE
YOYO.AspNetCore.ViewEngine.Razor支持.net core 2.0

### ISSUE THREAD

**Issue by tiandao-dongguan** [maxzhang1985/YOYOFx#12]
大神，.net core 2.0出来了，YOYO.AspNetCore.ViewEngine.Razo是否考虑支持一下呢？

**Comment by yoyofx** [comment]
好的，最近比较忙，下周我就更新上去

**Comment by RenshuozZ** [comment]
@maxzhang1985  易车的大神吗~可惜去面试聊得不错回来没信了~支持2.0吗现在

**Comment by yoyofx** [comment]
@RenshuozZ 基于nst 1.6的，理论上可以跑2.0上的；还有易车内部正在调整，过完年你可以再投投试试。

**Comment by RenshuozZ** [comment]
@maxzhang1985  感谢回复 我试试
