### ISSUE TITLE
请问有没有完整的文档

### ISSUE THREAD

**Issue by daya-prac** [maxzhang1985/YOYOFx#13]

**Comment by onestar1** [comment]
没有文档， 想学习下 autofac的内容

**Comment by yoyofx** [comment]
没有文档，这个项目主要是用于在 .NET Core没成熟之前，mono - .net core 2.0 之前的过度产品，用于过我做过的项目开发中； 鉴于目前.NET Core 和 ASP.NET Core Mvc 已经非常成熟，我已经决定不在维护这个项目了。

新关注我的新项目： https://github.com/yoyofx/yoyogo   使用Go语言复刻ASP.NET Core.
