### ISSUE TITLE
DI 注入

### ISSUE THREAD

**Issue by XiaoLongRenMengXin** [maxzhang1985/YOYOFx#15]
目前我正在想将nhibernate听过服务的方式注入到程序中,不知道您走过这条路可以给我提供一些帮助吗?我的想法是通过服务方式注册,其次在应用中将nhibernate session工厂绑定在http请求实例上,完成数据库访问的重复使用

**Comment by yoyofx** [comment]
可以参与EF的注入方式；

关注我的新项目： https://github.com/yoyofx/yoyogo   使用Go语言复刻ASP.NET Core.
