### ISSUE TITLE
Unable to load DLL 'libcaptchaimage.dll': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by dxp888** [maxzhang1985/YOYOFx#4]
我已经拷贝相关的dll到系统目录下了，但是还是提示这个错误，系统是window server 2008r2，是不是还需要安装什么组件？谢谢

**Comment by maxzhang1985** [comment]
libcaptchaimage.dll是C++组件,需要你自己编译，在Native目录下的 LibCaptchaImage子目录下编译这个项目。
