### ISSUE TITLE
希望路由支持命名空间

### ISSUE THREAD

**Issue by jianliulin** [maxzhang1985/YOYOFx#5]
路由可否支持命名空间，比如；

namespace CoreHost.Controllers.abc
{
    public class Home : Controller
  {      
        public dynamic Login()
        {
            return View("/Views/Login.cshtml");
        }
  }
}

1. 路由到 /abc/Home/Login 

2.添加一个从方法名转换获取路由的方法，如：string aaa = xxxxx(new abc.Home().Login)
  aaa=>"/abc/Home/Login "

2.  return View("/Views/Login.cshtml"); ==> 简化为  return View() 默认找 /Views/abc/Home/Login.cshtml文件，

**Comment by maxzhang1985** [comment]
@jianliulin 目前不考虑，命名空间的路由方式；去觉得你上次修改的代码，可以提交下，我可以借鉴一下。
